development:
  adapter: postgresql
  encoding: unicode
  database: mydb
  username: brittanygrebnova
  password: MilaGrebnova2013$

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
